feat(ProfilePageRedux): added new profile mockup
Satellite-im/Satellite-Absolute pull request #115
Opened 2021-08-30 14:48 UTC by nickjjang

After added mockup for profile, there are two problems.

- As you can see, there is padding of Settings screen for wrapping children component, so Profile image couldn't match the parent width like the mockup design.
- I used multiselect component for selecting locations and languages, but it needs to be updated in order to implement your design requirements. May I update it?

I also added components/interactables/Chip for global usage. Is there any problem with this?

2021-08-31 00:28 UTC, nickjjang commented
I moved Buttongroup component in marketplace to components and updated it.
You can confirm its usage in marketplace. I have been thinking about it, but it's simple yet.

2021-08-31 07:16 UTC, RetroPronghorn requested changes

2021-08-31 07:16 UTC, RetroPronghorn commented on assets/img/icon_badge1.svg
> +<svg width="24" height="23" viewBox="0 0 24 23" fill="none" xmlns="http://www.w3.org/2000/svg">
Let's remove these SVGs for now. just use generic font awesome icons. There are a few example badges. I don't want to forget about these placeholder ones when we move to prod.

2021-08-31 07:16 UTC, RetroPronghorn commented on components/interactables/Chip/Chip.vue
>    border-radius: 24px;
I know it's not part of this ticket, but can we move the border-radius: 24px to a global in the less files? I think we use it in quite a few places where we want rounded buttons.

2021-08-31 07:16 UTC, RetroPronghorn commented on components/tailored/marketplace/searchbox/Searchbox.html
>    <InteractablesInput
Also not part of this ticket, but can we open a new ticket in Jira to make the search input it's own standalone component so we may reuse it in other places where we may have different search filters but want the same input

2021-08-31 07:16 UTC, RetroPronghorn commented on pages/settings/profile/Profile.less
> +  margin-top: 32px;
Let's use either @normal-spacing or @light-spacing here, if you need a bit more multiply the value. This way we can change spacing globally.

2021-08-31 07:16 UTC, RetroPronghorn commented on types/profile/profile.ts
> +export enum ProfileBadgeType {
We have existing badges in the app for the badges next to users names, let's reuse those typings. It should be in the config file somewhere if you need a reference.

2021-08-31 18:49 UTC, nickjjang commented on components/tailored/marketplace/searchbox/Searchbox.html
>    <InteractablesInput
please open new ticket for this.

2021-08-31 19:06 UTC, nickjjang commented on assets/img/icon_badge1.svg
> +<svg width="24" height="23" viewBox="0 0 24 23" fill="none" xmlns="http://www.w3.org/2000/svg">
I added some font awesome icons seems like badges

2021-08-31 19:09 UTC, nickjjang commented on components/interactables/Chip/Chip.vue
>    border-radius: 24px;
I added spacing and corner rounding styles such as large, xlarge, xlight and xxlarge

2021-08-31 19:12 UTC, nickjjang commented on types/profile/profile.ts
> +export enum ProfileBadgeType {
I used badges without proper meanings, so in order to include them in config file, should I make them meaningful?

2021-09-02 20:20 UTC, nickjjang commented
I added tailored/user/search for User Search component.

2021-09-02 23:32 UTC, RetroPronghorn commented
@nickjjang please port this code to the page under the settings component. This should be straightforward.

2021-09-06 19:28 UTC, merged