Eric/SA-94
Satellite-im/Satellite-Absolute pull request #116
Opened 2021-08-30 22:48 UTC by genie-magic

Implement Chat Auto Scroll Component

2021-08-31 07:21 UTC, RetroPronghorn requested changes

2021-08-31 07:21 UTC, RetroPronghorn commented on components/ui/ChatScroll/ChatScroll.html
> +   {{$store.state.media.unreadMessage}} {{ $t('pages.chat.new_message') }}
please add spacing here around the {{$store so it is {{ $store.

2021-08-31 07:21 UTC, RetroPronghorn commented on components/ui/ChatScroll/ChatScroll.less
> +  scrollbar-color: #0984e3 transparent;
Please use @primary-color here.

2021-08-31 07:21 UTC, RetroPronghorn commented on components/ui/ChatScroll/ChatScroll.less
> +    border-radius: 6px;
I think this matches our normal border-radius, consider using @corner-rounding variable

2021-08-31 07:21 UTC, RetroPronghorn commented on components/ui/ChatScroll/ChatScroll.less
> +    background: #0984e3;
Please use a global color here from colors.less

2021-08-31 07:21 UTC, RetroPronghorn commented on components/ui/ChatScroll/ChatScroll.less
> +  border-radius: 6px;
Please use @corner-rounding-light here

2021-08-31 07:21 UTC, RetroPronghorn commented on components/ui/ChatScroll/ChatScroll.less
> +  background: #0984e3;
@primary-color

2021-08-31 07:21 UTC, RetroPronghorn commented on locales/en-US.js
> +      mark_as_read: 'MARK AS READ',
Instead of "mark as read" it should indicate "Jump To Current" nd when clicking this popup it should scroll to the bottom of the content.

2021-08-31 07:21 UTC, RetroPronghorn commented on store/media/state.ts
> +  unreadMessage: number
Use $mock.user.unreads instead, MediaState is reserved for WebRTC and Solana interactions

2021-08-31 07:21 UTC, RetroPronghorn commented on store/media/state.ts
> +  isScrollOver: boolean
Place this in UI state instead

2021-08-31 20:02 UTC, genie-magic commented
@RetroPronghorn  I updated the code that you pointed.

2021-09-03 09:17 UTC, genie-magic commented
@RetroPronghorn   I fixed conflicts.

2021-09-06 19:51 UTC, merged