fix(Enhancer): Fix 'After opening the Glyphs menu, user should be able to press it again to close it'
Satellite-im/Satellite-Absolute pull request #245
Opened 2021-11-10 12:38 UTC by genie-magic

Fix 'After opening the Glyphs menu, user should be able to press it again to close it'

2021-11-10 15:58 UTC, RetroPronghorn requested changes

2021-11-10 15:58 UTC, RetroPronghorn commented on components/tailored/messaging/enhancers/Enhancers.vue
> +      const chatToggleEnhancer = document.getElementById('chat-enhancer-toggle')
We should use a ref here instead of ID

2021-11-10 15:58 UTC, RetroPronghorn commented on components/tailored/core/chatbar/Chatbar.html
> +      id='chat-enhancer-toggle'
switch to ref="chat-enhancer-toggle"

2021-11-10 15:58 UTC, RetroPronghorn commented on components/tailored/messaging/enhancers/Enhancers.vue
> +      const chatToggleEnhancer = document.getElementById('chat-enhancer-toggle')
We can use something like 
`const chatToggleEnhancer = this.$refs.chatToggleEnhancer as HTMLElement` if we need to access dom funcitonality

2021-11-10 16:16 UTC, genie-magic commented on components/tailored/core/chatbar/Chatbar.html
> +      id='chat-enhancer-toggle'
But we can't access to other component's ref.. isn't it?

2021-11-10 17:53 UTC, RetroPronghorn commented on components/tailored/core/chatbar/Chatbar.html
> +      id='chat-enhancer-toggle'
Hmm yeah, we should instead use the mutation to toggle then.

2021-11-12 14:56 UTC, genie-magic commented
Will close this pull request and create with dev

2021-11-12 14:56 UTC, closed without merging