refactor(Typing Indicator): AP-37 - Typing indicator component now accepts an array of user names displaying up to 3 names, when 4+ names: displays many typing, and 0: nothing
Satellite-im/Satellite-Absolute pull request #279
Opened 2021-11-17 15:46 UTC by Jekrimo

**What this PR does** 📖
Typing indicator component now accepts an array of user names displaying up to 3 names, when 4+ names: displays many typing, and 0: nothing. This is a preparation for our user data models, will need more revision once permanent data structure is in place
**Which issue(s) this PR fixes** 🔨
AP-37
Fixes #
Multiple users typing
**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-11-18 06:33 UTC, WanderingHogan commented
can you also updated `components/tailored/core/chatbar/footer/Footer.vue` to pass the fake user into UiTypingIndicator using the users prop, in an array

2021-11-18 06:34 UTC, WanderingHogan requested changes

2021-11-18 06:34 UTC, WanderingHogan commented on components/ui/TypingIndicator/TypingIndicator.vue
> +    checkUsersTyping() {
Can you re-order these, so 0 is 0 instead of 3, and do something like this instead of the else: 

```  
checkUsersTyping() {
      if (this.users.length > 3){
        return 2
      }
      if(this.users.length > 0) {
        return 1
      }
      return 0
    }```

2021-11-19 07:40 UTC, WanderingHogan approved these changes

2021-11-19 19:02 UTC, genie-magic approved these changes

2021-11-19 19:36 UTC, merged