feat(Chatbar): can now paste images into chatbar
Satellite-im/Satellite-Absolute pull request #292
Opened 2021-11-20 22:01 UTC by jpanay

**What this PR does** 📖
Does a proper image upload when you paste an image into the chat bar

**Which issue(s) this PR fixes** 🔨
Stops image pastes from just glitching and disappearing and instead handles them properly
Also small typo fix in locales

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-11-21 20:37 UTC, stavares843 reviewed
@jpanay neat 🎉 

quick question, is this expected to handle all the upload process as well or is the aim of the PR only adding the box with the upload file within the chat bar?

2021-11-21 22:06 UTC, jpanay commented
This is just to handle copy pasting images into the chatbar so you can send
them

On Sun, Nov 21, 2021 at 3:37 PM Sara Tavares ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> @jpanay <https://github.com/jpanay> neat 🎉
>
> quick question, is this expected to handle all the upload process as well
> or is the aim of the PR only adding the box with the upload file within the
> chat bar?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Satellite-im/Satellite-Absolute/pull/292#pullrequestreview-811962599>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQYRRHPOMDLZ2KEFTQIPGGTUNFKADANCNFSM5IOMR2AA>
> .
>

2021-11-21 22:29 UTC, stavares843 commented
Thanks! Just to clarify, the sending action is not added right? I see the button but is not sending out the images.

2021-11-21 22:31 UTC, jpanay commented
It’s not I’ll open a ticket to get it sending for drag and drop and copy
paste

On Sun, Nov 21, 2021 at 5:29 PM Sara Tavares ***@***.***>
wrote:

> Thanks! Just to clarify, the sending action is not added right? I see the
> button but is not sending out the images.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Satellite-im/Satellite-Absolute/pull/292#issuecomment-974909142>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQYRRHNZOGBX5S67NBV27BTUNFXEFANCNFSM5IOMR2AA>
> .
>

2021-11-21 22:43 UTC, stavares843 commented
Thanks! 🎉

2021-11-21 23:05 UTC, stavares843 reviewed
feedback only related to the copy/pasting box and the copy/pasting images action, excluding the send action

1. If you copy paste a .TIFF image type, a icon appears but lacks a bit padding between the icon and the file name
<img width="1056" alt="Captura de ecrã 2021-11-21, às 22 47 54" src="https://user-images.githubusercontent.com/29093946/142782028-95950339-c4b6-4de6-97e6-1691715dac5c.png">

2. The below error appears on the console if you try to copy-paste an invalid image, such as grabbing a file and manually editing from .js to .png for example 

<img width="1403" alt="Captura de ecrã 2021-11-21, às 20 39 31" src="https://user-images.githubusercontent.com/29093946/142782061-1e7713c0-2144-4724-af9f-50718ebdbb11.png">

3. If you copy-paste an image with 100MB, the below error appears


<img width="1403" alt="Captura de ecrã 2021-11-21, às 20 39 31" src="https://user-images.githubusercontent.com/29093946/142782132-2faa6478-b38b-4ea7-b453-ae2a8109094f.png">

4. If you copy-paste an image with a file name with too many characters and use a resolution similar to a tablet, appears like the below image and doesn't scroll
<img width="1030" alt="Captura de ecrã 2021-11-21, às 20 33 27" src="https://user-images.githubusercontent.com/29093946/142782157-3dedb42a-26df-46b1-a2d2-99063fea1828.png">

5. If you try to copy-paste more than one image, we are not handling any user-facing message such as ''you can't copy-paste more than 1 file''

6. If you copy-paste an image and then copy-paste another on top, we don't warn the user with something like ''you already have an image pasted in your chat, are you sure you want to copy-paste again? the previous image will be lost'' or similar

cc @WanderingHogan I'd say these are more improvements that we could do going forward, I could add tickets for all these to be handled later and focus the technical resources on more relevant things, considering most of the feedback is more product-side related, but let me know if there's anything here on this list that you think it's worthing fixing on this PR.

2021-11-22 17:51 UTC, WanderingHogan requested changes

2021-11-22 17:51 UTC, WanderingHogan commented on components/tailored/core/chatbar/Chatbar.vue
> +      e.preventDefault()
Since we are just re-using the same function, can you rename it and only have it once, something like 'handleUpload' then have paste and drop both reference the same function

2021-11-22 18:09 UTC, WanderingHogan commented
@stavares843 i like your idea of adding more tickets for improvements later

2021-11-22 18:36 UTC, stavares843 commented
[AP-89](https://satellite-im.atlassian.net/browse/AP-89)
[AP-90](https://satellite-im.atlassian.net/browse/AP-90)
[AP-91](https://satellite-im.atlassian.net/browse/AP-91)
[AP-92](https://satellite-im.atlassian.net/browse/AP-92)
[AP-93](https://satellite-im.atlassian.net/browse/AP-93)
[AP-94](https://satellite-im.atlassian.net/browse/AP-94)
 

added 🎉 


for this PR the only changes requested to address are the one's from hogan's review @jpanay 

I added everything else on tickets to be handled later

2021-11-22 21:45 UTC, WanderingHogan approved these changes

2021-11-22 21:46 UTC, merged