Ap 67   new chat and community typehead bugs
Satellite-im/Satellite-Absolute pull request #294
Opened 2021-11-22 21:28 UTC by Jekrimo

**What this PR does** 📖
Fixes multiple user search modal issues
**Which issue(s) this PR fixes** 🔨
AP67
Fixes #
First - when the input box expands, the typeahead stays in the same place blocking the view. 

Second - if you typeahead for someone at the top of the list, they are floating until an event happens before bringing it down to the input box.

Third - When you typeahead and click a user, the text you were typing should be removed.

Other minor fixes that occurred while fixing bugs including styling updates.
**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-11-22 23:23 UTC, stavares843 approved these changes
tested, the 3 points referred on the tickets seem fixed 🔨 

@WanderingHogan in case you want to take a look if that's what's you were hoping as well. I noticed a small things also on the animation and on the padding on the users list and so on, but will add separate tickets for those to be handled later.

2021-11-23 20:03 UTC, WanderingHogan commented on components/tailored/settings/pages/user/Search.vue
> +      this.result = Users
@Jekrimo I know you didn't touch this, but can you change startsWith to includes in the searchResult method

2021-11-23 20:04 UTC, WanderingHogan requested changes
@Jekrimo I know you didn't touch this, but can you change `startsWith` to `includes` in the searchResult method of the search.vue file

2021-11-23 21:35 UTC, WanderingHogan approved these changes

2021-11-23 21:52 UTC, merged