fix(Chatbar): stops empty messages from sending
Satellite-im/Satellite-Absolute pull request #295
Opened 2021-11-22 22:24 UTC by jpanay

**What this PR does** 📖
Stops empty messages from sending

**Which issue(s) this PR fixes** 🔨
Now users cant send empty messages

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-11-22 22:42 UTC, stavares843 requested changes
going to a DM and entering a space and sending still works 

let me know if you need any more info!

2021-11-22 23:21 UTC, jpanay commented
Gotcha I'll fix it

On Mon, Nov 22, 2021 at 5:42 PM Sara Tavares ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> going to a DM and entering a space and sending still works
>
> let me know if you need any more info!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Satellite-im/Satellite-Absolute/pull/295#pullrequestreview-813089152>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQYRRHMCT2X6NVRSDP2TIXLUNLBMTANCNFSM5ISDFGLA>
> .
>

2021-11-23 14:04 UTC, stavares843 approved these changes
fixed ✅

2021-11-23 20:08 UTC, WanderingHogan approved these changes

2021-11-23 20:08 UTC, merged