Feature user state
Satellite-im/Satellite-Absolute pull request #299
Opened 2021-11-23 08:18 UTC by molimauro

**What this PR does** 📖
Introduce the userState component and spread it across the app so that the user state is consistent in all components that consume it
**Which issue(s) this PR fixes** 🔨
AP-30

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

2021-11-23 14:11 UTC, Jekrimo approved these changes

2021-11-24 00:44 UTC, RetroPronghorn requested changes

2021-11-24 00:44 UTC, RetroPronghorn commented on components/tailored/friends/add/Add.vue
>              accountId: this.accountID,
This is unrelated to your PR but we should make a point to just use "id" here instead of accountId. It's in the account object so the fact that it's the accountId can be inferred.

2021-11-24 00:44 UTC, RetroPronghorn commented on components/tailored/settings/pages/user/Search.vue
> -      result: Users,
Can we bind friends to mapState

2021-11-24 00:44 UTC, RetroPronghorn commented on components/tailored/settings/pages/user/Search.vue
> -      this.result = Users.filter((user) =>
mapState(['friends'])

2021-11-24 09:07 UTC, molimauro commented on components/tailored/friends/add/Add.vue
>              accountId: this.accountID,
yeah, I saw you reported this on channel. Closing 👍

2021-11-24 14:07 UTC, RetroPronghorn approved these changes

2021-11-24 14:07 UTC, merged