Fix(Login): Unlock should be persisted when store pin is enabled
Satellite-im/Satellite-Absolute pull request #302
Opened 2021-11-23 20:18 UTC by nickjjang

2021-11-23 20:22 UTC, stavares843 commented
quick question, how long is the PIN going to be stored? 30 days?

2021-11-23 20:23 UTC, nickjjang commented
Hey @stavares843
It uses localStorage so the variable is stored forever for now.

2021-11-23 20:26 UTC, stavares843 commented
thanks!

2021-11-23 20:29 UTC, stavares843 requested changes
the PIN is persisting 🎉 

2 things
- When you go directly to /#/auth/unlock still ask the PIN, the same doesn't happen on other URL's
- I'm seeing some issues after entering the PIN, getting stuck on linking, no relevant errors on the console, could you take a look if could be related to these code changes? I don't have this issue on the dev branch, I also rebooted the mac and deployed it again in case it was some local issue.

https://user-images.githubusercontent.com/29093946/143098924-6fdd45e5-9be4-4316-8fd6-fa98221b8135.mov

2021-11-24 04:51 UTC, nickjjang commented
Hi @stavares843 I fixed the issues you mentioned.

2021-11-24 06:28 UTC, RetroPronghorn requested changes

2021-11-24 06:28 UTC, RetroPronghorn commented on pages/auth/unlock/index.vue
> +        console.log(JSON.stringify(this.$store.state.prerequisites))
remove

2021-11-24 06:28 UTC, RetroPronghorn commented on pages/auth/unlock/index.vue
> +        console.log(JSON.stringify(this.$store.state.prerequisites))
after resolved looks good code wise.

2021-11-24 10:09 UTC, molimauro commented on plugins/thirdparty/persist.ts
> +const propertiesBlacklistWhenStorePin = ['prerequisites']
Can you add also 'friends.all' to `propertiesBlacklistWhenStorePin ` so that we do not store friends in the state? Thanks!

2021-11-24 12:12 UTC, nickjjang commented
Hi @RetroPronghorn, @molimauro 
I've fixed the issues you requested.

2021-11-24 12:13 UTC, nickjjang commented on plugins/thirdparty/persist.ts
> +const propertiesBlacklistWhenStorePin = ['prerequisites']
Fixed.

2021-11-24 12:14 UTC, nickjjang commented on pages/auth/unlock/index.vue
> +        console.log(JSON.stringify(this.$store.state.prerequisites))
Sorry for inconvemient.
I've removed colsole.log

2021-11-24 14:05 UTC, RetroPronghorn approved these changes

2021-11-24 15:10 UTC, molimauro approved these changes

2021-11-24 15:12 UTC, merged