feat(notifications): add browser alert and notification image
Satellite-im/Satellite-Absolute pull request #3538
Opened 2022-06-09 14:25 UTC by Jekrimo

**What this PR does** 📖
Adds browser push notification, adds profile thumbnail to in app notification

**Which issue(s) this PR fixes** 🔨

AP-1633

**Additional comments** 🎤
Needs some investigation into adding flair into the browser alert, ie. icon, theme color, localization, etc - ticket is made at AP-1755 & AP-1756

2022-06-09 18:29 UTC, WanderingHogan commented
![image](https://user-images.githubusercontent.com/2993032/172918820-ccab6609-4a1e-4fe5-b179-865413fdb9c1.png)

2022-06-09 21:59 UTC, WanderingHogan commented on utilities/Notifications.ts
> +    if (this.currentPlatform === PlatformTypeEnum.WEB) {
What do you think about using the built in notification api right above this for Web and Electron, modified a little bit?

<img width="354" alt="Screen Shot 2022-06-09 at 3 58 53 PM" src="https://user-images.githubusercontent.com/2993032/172952312-9ff86229-1fd7-4253-92df-3b220d45e530.png">

It lets us include our icon on the chrome notification
![image](https://user-images.githubusercontent.com/2993032/172952406-bedb6afc-94eb-4b32-8c12-66e7cf7420b2.png)

2022-06-09 22:00 UTC, WanderingHogan commented on utilities/Notifications.ts
> +    if (this.currentPlatform === PlatformTypeEnum.WEB) {
if you go this route you can remove the config import/parts too

2022-06-09 22:01 UTC, WanderingHogan commented on utilities/Notifications.ts
> +    if (this.currentPlatform === PlatformTypeEnum.WEB) {
icon might work with the image hash you passed, in too

2022-06-09 22:03 UTC, WanderingHogan commented on libraries/Textile/NotificationManager.ts
> +    const makeNotificationMessage = `New message from ${payload.from}`
can you add this to the translations, an example that would allow you to pass the from you can see if you search for `user.registration.username_error`

2022-06-09 22:04 UTC, WanderingHogan requested changes
can you check out the feedback and lmk

2022-06-09 22:53 UTC, WanderingHogan commented on libraries/Textile/NotificationManager.ts
> +    const makeNotificationMessage = `New message from ${payload.from}`
don't worry about this translation right now - as you are showing me in a DM we are having an issue using vues translation library outside of vue in the utilities

2022-06-09 22:57 UTC, Jekrimo commented on libraries/Textile/NotificationManager.ts
> +    const makeNotificationMessage = `New message from ${payload.from}`
https://media.tenor.com/images/f4ec7060f9dc5ed3bc0fb1d4e87f3e14/raw

2022-06-09 22:58 UTC, Jekrimo commented on libraries/Textile/NotificationManager.ts
> +    const makeNotificationMessage = `New message from ${payload.from}`
done and done

2022-06-09 23:01 UTC, Jekrimo commented on utilities/Notifications.ts
> +    if (this.currentPlatform === PlatformTypeEnum.WEB) {
YESSSS it worked with the image hash for the local!! yus, yus, yus. Thank you!

2022-06-09 23:09 UTC, Jekrimo commented on libraries/Textile/NotificationManager.ts
> +    const makeNotificationMessage = `New message from ${payload.from}`
@stavares843 If/when you test, can you tell us if the browser notification comes through already translated without us doing anything? (I feel like it should)

2022-06-09 23:16 UTC, WanderingHogan commented on utilities/Notifications.ts
> +    // if (this.currentPlatform === PlatformTypeEnum.WEB) {
@stavares843 @phillsatellite can we leave this commented code in for now and we remove it after this all evolves a little bit before EA

2022-06-09 23:16 UTC, WanderingHogan approved these changes

2022-06-10 15:46 UTC, phillsatellite approved these changes

2022-06-10 20:49 UTC, stavares843 requested changes
I tried this on both macOS and windows - Chrome.

Even after activating Chrome notifications on macOS settings, I received no alerts.

On windows, I got the pop-up asking permission for browser notifications, I said yes but no alerts.

2022-06-13 13:33 UTC, stavares843 commented
neat, thanks 🔨 checking

2022-06-15 10:52 UTC, iltumio commented on utilities/Notifications.ts
> +    // if (this.currentPlatform === PlatformTypeEnum.WEB) {
do we need to keep commented code?

2022-06-15 10:52 UTC, iltumio commented on utilities/Notifications.ts
>    sendNotification: any = this.sendNotifications
is it possible to use a proper type instead of 'any'?

2022-06-15 13:26 UTC, Jekrimo commented on utilities/Notifications.ts
> +    // if (this.currentPlatform === PlatformTypeEnum.WEB) {
Yeah, Hogan want's to leave this as we will be needing it for mobile and other such things.

2022-06-15 21:57 UTC, WanderingHogan approved these changes

2022-06-16 14:12 UTC, iltumio approved these changes
It's approved from my side. I found one small issue related to the notification removal. If you have 2 notifications and you try to remove one of them, both notifications are canceled

2022-06-16 16:36 UTC, Jekrimo commented
> works on windows
> 
> ![image](https://user-images.githubusercontent.com/29093946/174096668-3f690183-7b66-4ec3-86bf-fda8b52c230e.png)
> 
> but on macOS, even with the permissions activated on macOS settings I don't have any alerts from chat
> 
> <img alt="Captura de ecrã 2022-06-16, às 15 46 27" width="426" src="https://user-images.githubusercontent.com/29093946/174096719-5f1e4b65-fc9a-4764-873b-e79ae7ecc7ae.png">

Keep me posted if it's the mac's chrome settings like we discussed on discord

2022-06-16 22:54 UTC, stavares843 commented
yes will check 💥

2022-06-22 16:42 UTC, merged