Fixed issue and made CSS improvements
Satellite-im/Satellite-Absolute pull request #36
Opened 2021-07-12 09:38 UTC by jpanay

2021-07-13 18:58 UTC, RetroPronghorn requested changes

2021-07-13 18:58 UTC, RetroPronghorn commented on components/tailored/core/media/user/User.less
> +    z-index: 10;
For this, let's use the base index and add one. This will prevent us arbitrarily setting z index in the app. for example for tag use `z-index: calc(@base-z-index  + 1);` and for the other just use the `z-index: @base-z-index;`

2021-07-13 18:58 UTC, RetroPronghorn commented on components/tailored/core/media/Media.less
> +    overflow: scroll;
What does this accomplish, just want to be sure we actually want it to scroll.

2021-07-16 02:03 UTC, jpanay commented on components/tailored/core/media/Media.less
> +    overflow: scroll;
Makes it so that when it's not fullscreen and there's a lot of users you can scroll horizontally to see everyone instead of just having it cut off by the window

2021-07-16 02:03 UTC, jpanay commented on components/tailored/core/media/user/User.less
> +    z-index: 10;
fixed

2021-07-18 04:04 UTC, RetroPronghorn commented on components/tailored/core/media/Media.less
> +    overflow: scroll;
let's remove this as it's addressed in a different ticket in Jira with a different solution since scrolling is not optimal

2021-07-18 11:53 UTC, jpanay commented on components/tailored/core/media/Media.less
> +    overflow: scroll;
done

2021-07-19 12:15 UTC, merged