fix(linking): added timeout to linking process
Satellite-im/Satellite-Absolute pull request #5232
Opened 2022-10-12 10:12 UTC by ThomBos

### What this PR does 📖
- 

### Which issue(s) this PR fixes 🔨
- Resolve #4933 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2022-10-12 19:16 UTC, WanderingHogan requested changes

2022-10-12 19:16 UTC, WanderingHogan commented on pages/auth/unlock/index.vue
> +      }, 30000)
very minor, can you add the timeout time to config.ts

2022-10-13 07:48 UTC, josephmcg commented on pages/auth/unlock/index.vue
> +        this.error = `${this.$t('errors.timeout')}`
no need to wrap with template literals if it's pure js

2022-10-13 14:44 UTC, WanderingHogan approved these changes

2022-10-13 16:19 UTC, phillsatellite approved these changes

2022-10-13 16:19 UTC, merged