SA-49: Add "encrypted message" message to the top of direct/server chat
Satellite-im/Satellite-Absolute pull request #54
Opened 2021-07-23 22:19 UTC by KemoPaw

Top of message history it should have the notice that messages are encrypted. Please see the old app for an example of this.

2021-07-23 23:51 UTC, RetroPronghorn requested changes

2021-07-23 23:51 UTC, RetroPronghorn commented on pages/chat/direct/Direct.html
> +    <font-awesome-icon :icon="['fas', 'key-skeleton']" />
Small change, let's not add the solid icons yet, remove them from the package.JSON and use the outline version for now

2021-07-23 23:58 UTC, KemoPaw commented on pages/chat/direct/Direct.html
> +    <font-awesome-icon :icon="['fas', 'key-skeleton']" />
Okay, working on the fixes now!

2021-07-24 00:01 UTC, KemoPaw commented on pages/chat/direct/Direct.html
> +    <font-awesome-icon :icon="['fas', 'key-skeleton']" />
@RetroPronghorn just fixed it!

2021-07-24 04:00 UTC, merged